org: implementing
service: lambda-node-backend-template

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  environment:
    NODE_ENV: production
    FOO: ${env:FOO}

plugins:
  - serverless-offline

functions:
  app:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

custom:
  serverless-offline:
    reloadHandler: true