org: implementing
service: lambda-node-backend-template

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2

plugins:
  - serverless-offline

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY